# Generated by Django 4.1 on 2022-08-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_pickups_app', '0003_usersavedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedlocation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_pickups_app.profile'),
        ),
    ]
