# Generated by Django 4.1 on 2022-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_pickups_app', '0004_alter_usersavedlocation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='scrap_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
