# Generated by Django 4.1 on 2022-08-12 21:03

from django.db import migrations, models
import scrap_pickups_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_pickups_app', '0005_pickup_scrap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='scrap_image',
            field=models.ImageField(blank=True, null=True, upload_to=scrap_pickups_app.models.image_file_name),
        ),
    ]
