# Generated by Django 4.1 on 2022-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_pickups_app', '0007_alter_pickup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedlocation',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
